version: "3.9"

services:
  currency-api:
    build: .
    ports:
      - "3000:3000"  #port 3000 to host port 3000
    environment:  # Define environment variables to be passed to the container
      - API=${API}
      - TOKEN=${TOKEN}
      - PORT=3000